[package]
name = "ruby-liquid-rust"
version = "0.1.0"
authors = ["Maciej Bielecki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rutie = "0.7.0"

[lib]
name = "liquid_rust"
crate-type = ["cdylib"]
